/** Centralized query keys for cache invalidation */
export const queryKeys = {
  plants: ["masters", "plants"],
  materials: (params) => ["masters", "materials", params],
  vendorPOs: (params) => ["vendor", "pos", params],
  vendorPOInfinite: (params) => ["vendor", "pos", "infinite", params],
  poDetail: (poNumber) => ["vendor", "po", poNumber, "v3"],
  vendorInvoices: (params) => ["vendor", "invoices", params],
  vendorInvoicesInfinite: (params) => ["vendor", "invoices", "infinite", params],
  invoiceDetail: (id) => ["vendor", "invoice", id],
  dashboard: ["vendor", "dashboard"],
  vendorDashboardSummary: ["vendor", "dashboard", "summary"],
  vendorPOBalanceList: (params) => ["vendor", "pos", "balance", params],
  vendorPODetailBalance: (poNumber) => ["vendor", "po", "balance", poNumber],
  vendorMaterialBalance: ["vendor", "materials", "balance"],
  adminDashboard: ["admin", "dashboard"],
  adminBalanceDashboard: ["admin", "dashboard", "balance"],
  adminPOBalance: (params) => ["admin", "po-balance", params],
  adminVendorPOBalance: (code) => ["admin", "vendor", code, "po-balance"],
  adminMaterialBalance: (params) => ["admin", "materials", "balance", params],
  adminUploadHistory: (params) => ["admin", "po", "upload-history", params],
  adminUploadBatch: (id) => ["admin", "po", "upload-batch", id],
  adminVendors: (params) => ["admin", "vendors", params],
  adminPOs: (params) => ["admin", "pos", params],
  adminInvoices: (params) => ["admin", "invoices", params],
  auditLogs: (params) => ["admin", "audit", params],
  storageLocations: (plantCode) => ["masters", "storage", plantCode],
  openPOs: ["vendor", "pos", "open"],
  invoicePrint: (id) => ["vendor", "invoice", "print", id],
  poSyncHistory: (limit) => ["admin", "po-sync-history", limit],
};
